### ISSUE TITLE
Request for Code 128 support

### ISSUE THREAD

**Issue by robili** [maslick/koder#14]
The underlying Zbar lib supports GS1 128 / Code 128. Would be great to have that support here as well as it's a commonly used barcode.

<img width="168" alt="Screenshot 2021-09-13 at 20 10 17" src="https://user-images.githubusercontent.com/10404524/133141486-15c7a2a6-fab7-4cdc-ab6b-b1ffc1a784ce.png">

**Comment by maslick** [comment]
done ;)
