### ISSUE TITLE
Improving the readability for poor devices

### ISSUE THREAD

**Issue by phlcastro** [maslick/koder#22]
Hey mate,

first of all, nice work you have done here! I've tested a few times and it does works smoothly!

The thing is, when using some cheap Android devices that have bad cameras the scanner can't read the barcode.

Would that be a case to improve the original ZBar library or is there something we can do within koder?

Cheers

**Comment by maslick** [comment]
Hi! Could you provide some more details, e.g. which devices have your tested, their specs, camera resolution, etc.

**Comment by maslick** [comment]
You could also lower the frequency at which raw data is fed to the WASM service worker e.g. [here](https://github.com/maslick/koder/blob/master/src/index.js#L9) (react js example [1]) and [here](https://github.com/maslick/koder/blob/master/docs/main.js#L83) (vanilla js example [2]).

- In [1] canvas data (from the camera) is sent to the web worker every 250 ms or (4 times per second)
- In [2] the data is send every 600 ms.

You could play with these values to get an optimal result. QR/bar code recognition itself is run in a separate web worker thread and takes around 5 ms to process. 

You can also debug the actual frame rate (FPS).

**Comment by phlcastro** [comment]
Here are the device specs: [https://ztemobiles.com.au/optus-x-sight-2/](https://ztemobiles.com.au/optus-x-sight-2/)

I'll definitely play with the settings you mentioned above, but I guess it may have something to do with the camera quality + env light available. 

I know even with poor conditions its possible to read it, because I did some tests using this paid lib [https://www.scandit.com/products/web-sdk/](https://www.scandit.com/products/web-sdk/) and they can handle it pretty well.
I was hopping to get a similar performance with an open source solution like yours.

Cheers!

**Comment by maslick** [comment]
Yet another thing - disabling the crossfire will increase the area (raw data) sent to the Web worker (background thread), resulting in a longer processing time 2-5 ms (crossfire on) vs 10-12 ms (crossfire off). However, this should not affect performance much since the algorithm runs in a separate thread. 

I would hook your phone up to the PC and debug using Chrome Developer Tools, see the console, perhaps some warnings or error messages.

**Comment by phlcastro** [comment]
thanks mate! I'll give it a try and let you know of any progress I may get. really appreciate your help! cheers!
