### ISSUE TITLE
Barcode scanner doesn't work with Galaxy S10/ Galaxy A52s in Google Chrome

### ISSUE THREAD

**Issue by efedericomedina** [maslick/koder#64]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [README.md](https://github.com/maslick/koder/blob/master/README.md)
- [x] I've searched for [previous similar issues](https://github.com/maslick/koder/issues) and didn't find any solution

I tried to use the scanner in my Samsung Galaxy 10 and I couldn't make it work. I tested it on Google Chrome, the camera does not get to focus and the image gets blurry though I tried it out with Firefox and it worked fine with the same phone.
 
I have tested the scanner also on Samsung galaxy A52s and I had the same results with Google Chrome.

Steps to reproduce the behaviour using the demo page.

1- Open Chrome and go to  https://qr.maslick.tech/ 
2-  Start scanner 
3-  Aim camera at book's  barcode.

Expected behavior

Scanned barcode text.

 - Device: [Galaxy S10][Galaxy A52s]
 - OS: [Android 12]
 - Browser [Chrome]
 - Version [98]

**Comment by maslick** [comment]
1. Did you try adding Koder to Home screen (Add to Home Screen)?
2. Does the camera start?
3. Are there any errors/warnings in the console? Try open Developer Tools on your Laptop and connect to your phone
4. Can you provide any screenshots?

**Comment by maslick** [comment]
Can you post an example of the barcode you are trying to scan?

**Comment by efedericomedina** [comment]
Hi, 

Did you try adding Koder to Home screen (Add to Home Screen)?

yes, I tried that. the camera is blurry.

Does the camera start?

yes

Are there any errors/warnings in the console? Try open Chrome Developer Tools on your Laptop and connect to your phone

There are no errors in the console.

Can you provide any screenshots?

![WhatsApp Image 2022-02-09 at 11 33 44](https://user-images.githubusercontent.com/34874093/153180722-0091bcd2-931e-4a2d-b415-87b9ddc48cb4.jpeg)

**Comment by maslick** [comment]
I guess your barcode is broken, I can see a couple white dots on some thin bars. Try scanning this code 
![image](https://user-images.githubusercontent.com/5644706/153182069-26177981-7528-41f2-bef3-4c20c8880467.png)
![IMG_CAF16D113B41-1](https://user-images.githubusercontent.com/5644706/153182173-a8a2ccbd-cd05-426b-a53f-f7da270caf69.jpeg)

**Comment by maslick** [comment]
Here's another one from a real book:
![1](https://user-images.githubusercontent.com/5644706/153183515-e66bcf48-5b88-4114-b98b-3050f2f4d3fc.jpeg)
![2](https://user-images.githubusercontent.com/5644706/153183503-d7b96668-8523-4c91-973b-a46de5167ec9.jpeg)

**Comment by efedericomedina** [comment]
It worked with that code on Chrome. I checked with different books here and if its a normal book barcode then it does not work.

**Comment by maslick** [comment]
See my comment above

**Comment by efedericomedina** [comment]
which phone have you used to scan?

**Comment by maslick** [comment]
iPhone 11 Pro / Chrome Browser

**Comment by maslick** [comment]
So I presume it's the camera/image quality problem you're facing...

**Comment by efedericomedina** [comment]
yes, it is strange though that in Firefox the image is good and it works well but not in Chrome :o

**Comment by sesam** [comment]
We've worked with barcode scanning for a few years, and noticed some strange things:
- Android phones have multiple logical cameras (even on some old phones with a single camera)
- Chrome may pick a different camera "by default" depending on whether you're running in "standalone" or "fullscreen mode"
- there's no way to reliably detect which camera is the not blurry one.

Typically we've seen a blurry camera getting chosen sporadically and our best cure so far is to try to detect the list of cameras and have an array of deviceId of the cameras we've seen working out well.

(The blurry is typically a wide-angle camera)

**Comment by albi90** [comment]
I have had similar issues on my Galaxy Z Flip 3, im my case i was making a VueJS component from this excellent implementation of zbar and there are a few things i have found.

1) You need to add support for camera selection the default camera is not always the best it in most cases its a wide angle camera and this doesn't work well for decoding.

2) The canvas size makes a big difference, I'm my case I made the canvas 600x300 and this gave me a good sweet spot for scanning.

3) My first test was on the main thread and this worked really well with the exception of slowing down other operations after moving this to a webworker on Android my scans became super slow like 3-4 sec after alot of debugging and adding the frame time to the postmessage from the main thread and passing this back after the detection i could see the processing times for the frame and detection were fast like 10 or 11ms but when checking the original frame time to the time when the message is received back on the main thread there was a delay of 3-4 sec, after alot of playing around I found that if I only send the frame to worker every 20ms then everything runs super smooth full end to end detection of 11-12ms

@maslick thanks for this great implementation with a bit of playing around its extremally fast and quite accurate

**Comment by albi90** [comment]
@maslick thanks will try increasing the scan rate to see if it has much effect on my devices your correct its probably a bit fast 50fps, 250ms seems slow to me though was there any particular devices that required lower frame rates.

**Comment by maslick** [comment]
Closing for now...
