### ISSUE TITLE
Barcode scanner doesn't work with Iphone 13 Pro

### ISSUE THREAD

**Issue by efedericomedina** [maslick/koder#65]
- [x] I've gone through the [README.md](https://github.com/maslick/koder/blob/master/README.md)
- [x] I've searched for [previous similar issues](https://github.com/maslick/koder/issues) and didn't find any solution

I tried the barcode scanner with Iphone 13 pro using Safari, Chrome and Firefox and it didn't work. The camera doesn't focus and the image gets blurry when trying to read a barcode.

Steps to reproduce the behaviour using the demo page.

1- Open browser and go to https://qr.maslick.tech/
2- Start barcode scanner
3- Aim camera at book's barcode.

Expected behavior

Scanned barcode text.

Device: [Iphone 13 Pro]
OS: [ iOS 15.0]
Browser [Safari, Chrome and Firefox]

**Comment by maslick** [comment]
@efedericomedina Can you post an example of the barcode you are trying to scan?

**Comment by efedericomedina** [comment]
Did the webapp ask for your Camera permissions? 

Yes.

Did the camera start?

Yes

 Can you provide a screenshot? 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/34874093/153187071-6e491f5e-b944-412d-a0cb-c4f923e1fcc2.png)

**Comment by efedericomedina** [comment]
we tried with deafferents books and sometimes it works and sometimes it doesn't and that is depending on the lighting. though the focus is blurry. I have a Iphone12 and there it works fine.

**Comment by maslick** [comment]
This is obviously due to the blurry focus. Closing.
