### ISSUE TITLE
ALL THE WAY UP PARTNER 💪

### ISSUE THREAD

**Issue by MikeBennington2000** [maslick/koder#68]
First thing this is an amazing work...
You saved me allot of time thanx lots.
But I have questions
-**How can I enable all barcode types detection supported by ZBAR ?**
-**When scanning EAN-13 barcodes that starts with zero, it removes the leading zero and consider it as a UPC-A barcode. How to solve this ?**

_MUCH LOVE..._ ❤

**Comment by MikeBennington2000** [comment]
I am using the html javascript version in docs folder

**Comment by maslick** [comment]
@MikeBennington2000 could you post an example EAN-13 code here? Thnx!

**Comment by maslick** [comment]
https://support.honeywellaidc.com/s/article/Can-EAN13-symbols-start-with-a-leading-zero
