### ISSUE TITLE
Angular example to reference

### ISSUE THREAD

**Issue by dylanvdmerwe** [maslick/koder#71]
**Is your feature request related to a problem? Please describe.**
Currently you have a plain JS and a React version. Missing is an Angular component that can be easily integrated. 

**Describe the solution you'd like**
It would be incredible to have an Angular example to look at. It would still be based off the NPM package, but the usage thereof would be wrapped in an Angular demo. 

**Describe alternatives you've considered**
Sure, it's possible to look through either the React or vanilla code and create a component, but it would be quite time consuming, especially for people who are not as familiar with doing things that way. Service workers also become quite complicated.

**Comment by GitSkelly** [comment]
Are there any plans or resources to look at for this issue?
