### ISSUE TITLE
Webpack Upgrade - Angular 14

### ISSUE THREAD

**Issue by joeldhenry** [maslick/koder#76]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [README.md](https://github.com/maslick/koder/blob/master/README.md)
- [x] I've searched for [previous similar issues](https://github.com/maslick/koder/issues) and didn't find any solution

**Describe the bug**
Using in angular 14 fails to compile due to newer Webpack version.

**To Reproduce (observed behavior)**
install & import koder into angular 14 project

**Logs/output**
```
./node_modules/@maslick/koder/zbar.js:34:20-43 - Error: Module not found: Error: Can't resolve 'path' in '[project]/node_modules/@maslick/koder'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

./node_modules/@maslick/koder/zbar.js:35:17-30 - Error: Module not found: Error: Can't resolve 'fs' in '[project]/node_modules/@maslick/koder'
```

**Comment by maslick** [comment]
Perhaps, this [1] should fix it. Closing since it doesn't relate to the library itself. You should know how to bundle your resources.

[1] https://stackoverflow.com/questions/50202948/update-to-angular-v6-module-not-found-error-cant-resolve-fs/63427821#63427821
