### ISSUE TITLE
Not able to indian AADHAAR card

### ISSUE THREAD

**Issue by harishfalco** [maslick/koder#79]
I was trying this QR code reader on mobile. It was unable to read the QR code on Indian AADHAAR cards. Please let me know on how to deal with it.
![aadhaar_image (1)](https://github.com/maslick/koder/assets/62054469/ae32579e-9fe7-4bd6-9f2f-8310b0d3d61e)

**Comment by maslick** [comment]
please, provide a smoother picture of higher quality
