### ISSUE TITLE
Halftone QR support

### ISSUE THREAD

**Issue by savikko** [maslick/koder#81]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [README.md](https://github.com/maslick/koder/blob/master/README.md)
- [x] I've searched for [previous similar issues](https://github.com/maslick/koder/issues) and didn't find any solution

I was evaluation this package and this looks good, thanks for creating this!

But, as I dived to custom QR code generation, I found somewhat cool project: https://github.com/fangj/Halftone-QRCode-Generator
More about this on https://backdrifting.net/post/016_halftone_qr

Anyways, for some reason I could not get any of those codes correctly read by using https://koder-prod.web.app

This is totally not priority case, but I am more interested about finding out why those actually don't work.

I am using Pixel 7 here, if that is somehow relevant.

**Comment by maslick** [comment]
In fact, Koder is able to decode these types as well!

I tried to decode these example images found here [1].
<img width="761" alt="Screenshot 2023-09-12 at 15 12 24" src="https://github.com/maslick/koder/assets/5644706/828b34c9-c6c8-4b7a-95d9-9af15a8988d9">


[1] http://vecg.cs.ucl.ac.uk/Projects/SmartGeometry/halftone_QR/halftoneQR_sigga13.html

**Comment by maslick** [comment]
![image](https://github.com/maslick/koder/assets/5644706/d4058839-66c3-4a17-bbcb-da1acd3d2ecc)

**Comment by savikko** [comment]
> Give it a try https://kameroon.web.app

I need to read little more about this. Seems to be working, but I did not yet understand the general architecture of this:
Where is the service part there, what is actually sent to Kameroon server? Video stream or images or something else?

Still, it seems there is something wrong with my device. It takes a long time to read any code. I succeeded reading those halftone-QRs once in a while, but usually it takes very long (meaning tens of seconds).

**Comment by maslick** [comment]
> I need to read little more about this. Seems to be working, but I did not yet understand the general architecture of this: Where is the service part there, what is actually sent to Kameroon server? Video stream or images or something else?
* The primary scenario is when you aim to shift the responsibility of QR/barcode scanning away from your web application. There's no Kameroon server whatsoever, it's just a static web-app. The actual scanning/recognition happens on the user's device. I have 2 example web apps to get you started: [react app](https://kameroon-demo.web.app/) (source code [here](https://github.com/maslick/kameroon-demo)) and [vanilla js app](https://kameroon-demo-js.web.app/) (source code [here](https://github.com/maslick/kameroon-demo-js)).
* If you just want to scan a QR/bar code, then you can just visit https://kameroon.web.app. It works in the same way as Koder.

> Still, it seems there is something wrong with my device. It takes a long time to read any code. I succeeded reading those halftone-QRs once in a while, but usually it takes very long (meaning tens of seconds).

**Comment by maslick** [comment]
> > I need to read little more about this. Seems to be working, but I did not yet understand the general architecture of this: Where is the service part there, what is actually sent to Kameroon server? Video stream or images or something else?
> 
> * The primary scenario is when you aim to shift the responsibility of QR/barcode scanning away from your web application. There's no Kameroon server whatsoever, it's just a static web-app. The actual scanning/recognition happens on the user's device. Then the result of the scan (encrypted using RSA-OAEP `public_key` that you provide in the query parameter) is sent back to your web app (as a query parameter to the `redirect_url` you specify in the query parameter). I have 2 example web apps to get you started: [react app](https://kameroon-demo.web.app/) (source code [here](https://github.com/maslick/kameroon-demo)) and [vanilla js app](https://kameroon-demo-js.web.app/) (source code [here](https://github.com/maslick/kameroon-demo-js)).
> * If you just want to scan a QR/bar code, then you can just visit https://kameroon.web.app. It works in the same way as Koder.
> 
> > Still, it seems there is something wrong with my device. It takes a long time to read any code. I succeeded reading those halftone-QRs once in a while, but usually it takes very long (meaning tens of seconds).
> 
> The problem may be in the focus. My iPhone 13 Pro automatically switches cameras (macro/normal) depending on the distance to the object. Your problem might be that you can't focus on the QR code, so the WASM worker receives a blurry image and cannot recognize the QR/bar code.

**Comment by maslick** [comment]
@savikko can I close this issue?

**Comment by savikko** [comment]
Closing the issue. Probably something related to focus. All good!
